//
// Starlight DMA Firmware - Donor Device Configuration
// AUTO-GENERATED by donor_to_coe.py -- DO NOT EDIT MANUALLY
//
// Donor: VID=0x14C3 DID=0x7925 REV=0x00
//        SVID=0x1A3B SDID=0x6002
//        Class=0x028000
//

`ifndef STARLIGHT_DONOR_CFG_SVH
`define STARLIGHT_DONOR_CFG_SVH

// Device Serial Number (DSN) from donor extended config space
localparam [63:0] DONOR_DSN = 64'h0000000000000000;

// Device IDs (for reference - these go into the Vivado PCIe IP core, not RTL)
localparam [15:0] DONOR_VENDOR_ID          = 16'h14C3;
localparam [15:0] DONOR_DEVICE_ID          = 16'h7925;
localparam [7:0]  DONOR_REVISION_ID        = 8'h00;
localparam [15:0] DONOR_SUBSYSTEM_VENDOR   = 16'h1A3B;
localparam [15:0] DONOR_SUBSYSTEM_DEVICE   = 16'h6002;
localparam [23:0] DONOR_CLASS_CODE         = 24'h028000;

`endif
