# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/angel/Desktop/starlight-immortal75t/firmware/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
